### ISSUE TITLE
update build script to add default experiments to synced directory

### ISSUE THREAD

**Issue by ben-jones** [iclab/centinel#95] opened 2014-10-31 18:34 UTC
add functionality in the build script to copy the default set of experiments from the package into the synced directory, not stored separately.

**Comment by rpanah** [comment] 2015-03-30 20:52
There's no "default" set of experiments. The decision was made not to include any experiments with the client so that it won't run any tests before giving consent.
@ben-jones, if this solves the issue, feel free to close it.

**Comment by ben-jones** [comment] 2015-03-30 21:01
If that is what we want to do, then we should a) remove the experiments from the package build and b) ensure that we are actually pulling from the correct experiment directory before pushing the package. 

We should update the documentation for building accordingly and we can close this issue after we update the documentation.

**Comment by rpanah** [comment] 2015-04-06 21:42
@ben-jones, removed path from package build. Updated the [package build](https://github.com/iclab/centinel/wiki/Building-the-pip-package) wiki page.

**Closed** 2015-04-07 16:16 UTC
Labels: bug

**Comment by ben-jones** [comment] 2015-04-07 19:55
@rpanah, you didn't add this on the current iteration, but can you clarify what you mean by this:
"Note: always update the version in the master branch instead of dev. This will save you some headache when rebasing (otherwise you'll encounter one conflict per version bump for setup.py and centinel/__init__.py)."

Are you suggesting that people push their changes from dev to master? There are other changes in dev that could cause issues with master.

**Comment by rpanah** [comment] 2015-04-07 19:57
No, I'm asking them to do version change (and *only* version change) in the master branch to avoid merge conflicts caused by applying other (dev branch-specific) changes when rebasing from master.
